plugins {
	id 'net.fabricmc.fabric-loom' version '1.17-SNAPSHOT'
	id 'maven-publish'
    id 'com.modrinth.minotaur' version '2.9.0'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {

}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	// Publish the mod's source alongside the compiled jar.
	withSourcesJar()
	toolchain.languageVersion = JavaLanguageVersion.of(25)

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}

static List<String> expandVersions(String range) {
    def parts = range.split("-")

    if (parts.length == 1) {
        return [range] as String[]
    }

    def startVersion = parts[0]
    int end = parts[1].toInteger()

    def versionParts = startVersion.split("\\.")
    int start = versionParts.last().toInteger()
    def prefix = versionParts[0..-2].join(".")

    return (start..end)
            .collect { "${prefix}.${it}".toString() }
}

modrinth {
    token = System.getenv("MODRINTH_TOKEN")

    projectId = project.modrinth_id

    versionNumber = project.version
    versionName = "World Install Button ${project.version}"
    versionType = "release"

    uploadFile = jar

    gameVersions = expandVersions(project.modrinth_version)
    loaders = ["fabric"]
}
